### PR TITLE
Add new component owners to the list

### PR DESCRIPTION
**Pull request by scholzj**
This PR adds new component owners to the list in this repository. They were all approved by maintainers and all accepted the invitation.

### CODE REVIEW

**Comment by scholzj** [comment]
@see-quick @matthew-chirgwin @PaulRMellor @mstruk @stanlyDoge Please let me know if you want to use another email or change anything. I took the emails from the commit DCO signofs.

**Comment by sknot-rh** [comment]
Hi. OK for me.

**Review by ppatierno — APPROVED** [review]

**Comment by PaulRMellor** [comment]
Thanks. Good for me.

**Comment by matthew-chirgwin** [comment]
LGTM - thanks!

**Review by Frawless — APPROVED** [review]

**Comment by mstruk** [comment]
Looks good to me as well.

**Review by samuel-hawker — APPROVED** [review]

**Pull request merged**
